### ISSUE TITLE
Unreadable text and does not follow system theme

### ISSUE THREAD

**Issue by in4matix** [cankurttekin/PinIt-Gnome-Extension#1]
Ubuntu 22.04. Dark shell theme.

![Screenshot from 2024-06-13 05-48-11](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/c16c85e0-6954-4c7c-854d-93941ae0a05f)

**Comment by cankurttekin** [comment]
Hey, thanks for your feedback. 
I added dark theme to dialog window. I pushed an updated version to extension.gnome.org, it should be available after review. Can you try it when new version available?
![dialogdark](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/29798399/8d411381-c1eb-40e6-a5f8-b46212b87743)

**Comment by in4matix** [comment]
Awesome! Will give it a try and report back here.

**Comment by in4matix** [comment]
@cankurttekin , thanks, works great now, but I see you are most likely going to drop future updates for Gnome 42 (Ubuntu 22). I hope that's not the case?

**Comment by cankurttekin** [comment]
I use both gnome 42 on my pop os machine and gnome 46 on fedora. I will try to fix if there is an issue with any of them till cosmic de comes to pop os. You can always report it.
