### ISSUE TITLE
Entry box half hidden

### ISSUE THREAD

**Issue by Scridgeon** [cankurttekin/PinIt-Gnome-Extension#3]
I installed version 7 of the extension from the Gnome Extensions site. Clicking the pin icon in the topbar presents the input box at the very top of the screen and cutoff.

![image](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/18316138/2699f2ff-68e6-490e-a7bd-8dae064a75d8)

**Comment by cankurttekin** [comment]
Thank you for reporting! Are you using extended monitors? I completely changed the drawing of ui; I probably fixed your problem too. Can you try after updating?

**Comment by Scridgeon** [comment]
I just installed version 11 and it's failing to activate. Below is the error that I'm seeing in Extension Manager after logging back into Gnome. I'm on Fedora, Gnome 46 if that helps at all.

![image](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/18316138/29a28616-3a4c-4ab4-ba28-6e7563de7d53)

**Comment by cankurttekin** [comment]
Oh, yes i noticed that i forgot to compile and push everything. Well, thanks again, it fixed and guess will be on gnome.extension.org shortly as version 12.

**Comment by Scridgeon** [comment]
Just loaded version 12 and the input box is fully functional. Thank you for fixing this so quickly.

![image](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/18316138/02b59933-2eae-47ae-9274-cb1020f8b792)
